# Playwright 测试配置文件
# 支持多环境配置，默认使用 test 环境

# 当前环境设置
current_environment: test

# 环境配置
environments:
  test:
    name: "测试环境"
    browser_timeout: 30000        # 浏览器超时时间(毫秒)
    navigation_timeout: 60000     # 页面导航超时时间(毫秒)
    element_timeout: 10000        # 元素操作超时时间(毫秒)
    headless: false                # 是否无头模式
    slow_mo: 0                    # 慢动作延迟(毫秒)
    video_record: true            # 是否录制视频
    screenshot_on_failure: true   # 失败时是否截图
    parallel_workers: 4           # 并行工作进程数
    retry_times: 2                # 重试次数

  prod:
    name: "生产环境"
    browser_timeout: 45000
    navigation_timeout: 90000
    element_timeout: 15000
    headless: true
    slow_mo: 0
    video_record: false
    screenshot_on_failure: true
    parallel_workers: 8
    retry_times: 3

  dev:
    name: "开发环境"
    browser_timeout: 20000
    navigation_timeout: 30000
    element_timeout: 8000
    headless: false               # 开发时显示浏览器
    slow_mo: 100                  # 开发时慢速执行
    video_record: false
    screenshot_on_failure: true
    parallel_workers: 2
    retry_times: 1

# 浏览器配置
browser:
  default: chromium
  supported: [chromium, firefox, webkit]
  args:
    - "--no-sandbox"
    - "--disable-dev-shm-usage"
    - "--disable-gpu"
    - "--disable-web-security"
    - "--allow-running-insecure-content"
    - "--disable-features=VizDisplayCompositor"

# 视口配置
viewport:
  width: 1920
  height: 1080

# 上下文配置
context:
  ignore_https_errors: true
  javascript_enabled: true
  accept_downloads: true
  locale: "zh-CN"
  timezone_id: "Asia/Shanghai"

# 截图配置
screenshot:
  full_page: true
  quality: 90
  type: "png"

# 日志配置
logging:
  level: "INFO"
  format: "%(asctime)s | %(levelname)s | %(message)s"
  date_format: "%Y-%m-%d %H:%M:%S"